export { TopNavigation } from './TopNavigation'
export { PatientContextSidebar } from './PatientContextSidebar'
export { CommandPalette } from './CommandPalette'
export { VoiceCommand } from './VoiceCommand'
export { SmartNotifications } from './SmartNotifications'
export { PatientPhoto } from './PatientPhoto'
export { HandoffGenerator } from './HandoffGenerator'
export { MobileQRCode } from './MobileQRCode'
export { CollaborativeCursors, useCollaborators } from './CollaborativeCursors'
export { AIInsightStrip, generateSampleInsights } from './AIInsightStrip'

